trigger:
  - master

stages:
  - stage: Deploy
    displayName: Deploy Azure Resource Manager Template
    jobs:
      - job: Deploy
        displayName: Deploy Template
        pool:
          vmImage: 'windows-2019'
        steps:
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: InfrastructureARMServiceConnection
              action: Create Or Update Resource Group
              deploymentMode: Complete
              resourceGroupName: scheduling-prod
              templateLocation: Linked artifact
              csmFile: $(System.DefaultWorkingDirectory)/infrastructure.json
